Marriott.Client.Web/Models/CheckIn/AllocateRoom.cs
using System;
using System.ComponentModel;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class AllocateRoom
    {
        public Guid ReservationId { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        public int RoomTypeId { get; set; }

        [DisplayName("Reservation Id")]
        public int ExternalId { get; set; }
        public bool RoomAllocationFailed { get; set; }
        public int RoomNumber { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/CheckIn.cs
using System;
using System.ComponentModel;
using Marriott.Business.Billing;
using Marriott.Business.Guest;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class CheckIn
    {
        public Guid ReservationId { get; set; }

        public Business.Reservation.ConfirmedReservation Reservation { get; set; }
        public GuestInformation GuestInformation { get; set; }
        public PaymentInformation PaymentInformation { get; set; }

        [DisplayName("Room Type")]
        public string RoomTypeName { get; set; }

        [DisplayName("Room Rate")]
        public double RoomRate { get; set; }

        [DisplayName("Total Room Rate")]
        public double TotalRoomRate { get; set; }

        [DisplayName("Room Number")]
        public int RoomNumber { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/Confirmation.cs
namespace Marriott.Client.Web.Models.CheckIn
{
    public class Confirmation
    {
        public int RoomNumber { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/ReservationInformation.cs
using System;
using System.ComponentModel;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class ReservationInformation
    {
        public int ExternalId { get; set; }

        [DisplayName("Check In")]
        public DateTime CheckIn { get; set; }

        [DisplayName("Check In")]
        public DateTime CheckOut { get; set; }

        [DisplayName("Room Type")]
        public string RoomTypeName { get; set; }

        [DisplayName("Total Nights of Stay")]
        public int TotalNightsOfStay { get; set; }

        [DisplayName("Room Rate per Night")]
        public double RoomRate { get; set; }

        [DisplayName("Total Room Rate")]
        public double TotalRoomRate { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/RoomAllocationResult.cs
using System.ComponentModel;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class RoomAllocationResult
    {
        public int RoomNumber { get; set; }
        public Result Result { get; set; }
    }

    public enum Result
    {
        Succeeded,
        [Description("In Progress")]
        InProgress,
        Failed
    }
}

Marriott.Client.Web/Models/CheckIn/Search.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class Search
    {
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        public List<SearchResult> Results { get; set; } = new List<SearchResult>();

        public bool SearchExecuted { get; set; }
    }

    public class SearchResult
    {
        public Guid ReservationId { get; set; }
        public int ExternalId { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        public string FullName { get; set; }
        public string RoomType { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/VerifyGuestInformation.cs
using System;
using System.ComponentModel;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class VerifyGuestInformation
    {
        public Guid ReservationId { get; set; }

        public Business.Reservation.ConfirmedReservation Reservation { get; set; }

        [DisplayName("Room Type")]
        public string RoomTypeName { get; set; }

        [DisplayName("Room Rate per Night")]
        public double RoomRate { get; set; }

        [DisplayName("Total Room Rate")]
        public double TotalRoomRate { get; set; }
    }
}

Marriott.Client.Web/Controllers/CheckInController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Marriott.Business.Billing;
using Marriott.Business.Billing.Commands;
using Marriott.Business.Guest;
using Marriott.Business.Guest.Commands;
using Marriott.Business.RoomInventory.Commands;
using Marriott.Client.Web.Composers.CheckIn;
using Marriott.Client.Web.Extensions;
using Marriott.Client.Web.Models.CheckIn;
using NServiceBus;
using AllocateRoom = Marriott.Business.RoomInventory.Commands.AllocateRoom;
using CheckIn = Marriott.Client.Web.Models.CheckIn.CheckIn;

namespace Marriott.Client.Web.Controllers
{
    public class CheckInController : Controller
    {
        private const string CheckIn = "checkin";
        public static readonly string ProgressBarText = "Search, Verify Guest Information, Verify Payment Information, Allocate Room, Confirmation";

        private readonly IEndpointInstance endpoint;
        private readonly CheckInComposer composer;

        public CheckInController(IEndpointInstance endpoint, CheckInComposer composer)
        {
            this.endpoint = endpoint;
            this.composer = composer;
            ViewBag.ActiveNavBarItem = NavigationBarItem.FrontDesk;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new Search());
        }

        [HttpPost]
        public async Task<ActionResult> Index(Search model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model = await composer.ComposeSearchResults(model);
            model.SearchExecuted = true;

            return View(model);
        }

        //TODO: is there any way to make this a POST?
        [HttpGet]
        public async Task<ActionResult> VerifyGuestInformation(Guid reservationId)
        {
            var model = await composer.ComposeVerifyGuestInformation(reservationId);

            await endpoint.Send(new AllocateRoom { ReservationId = reservationId, RoomTypeId = model.Reservation.RoomTypeId, CheckIn = model.Reservation.CheckIn, CheckOut = model.Reservation.CheckOut });

            var checkIn = new CheckIn
            {
                ReservationId = reservationId,
                Reservation = model.Reservation,
                RoomTypeName = model.RoomTypeName,
                RoomRate = model.RoomRate,
                TotalRoomRate = model.TotalRoomRate
            };
            Session[CheckIn] = checkIn;

            return View(model);
        }

        //[ChildActionOnly] may only be invoked synchronously: http://stackoverflow.com/questions/24072720/async-partialview-causes-httpserverutility-execute-blocked-exception
        [HttpGet]
        [ChildActionOnly]
        public ActionResult ReservationInformation(Guid reservationId)
        {
            var model = composer.ComposeReservationInformation(reservationId);
            return PartialView("_ReservationInformation", model);
        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult GuestInformation(Guid reservationId)
        {
            var model = composer.ComposeGuestInformation(reservationId);
            return PartialView("_EditGuestInformation", model);
        }

        [HttpPost]
        public ActionResult VerifyGuestInformation(GuestInformation model)
        {
            if (!ModelState.IsValid)
            {
                return View("VerifyGuestInformation", new VerifyGuestInformation { ReservationId = model.ReservationId });
            }

            endpoint.Send(new SaveGuestInformation { GuestInformation = model });

            var checkIn = (CheckIn)Session[CheckIn];
            checkIn.GuestInformation = model;
            Session[CheckIn] = checkIn;

            return RedirectToAction(nameof(VerifyPaymentInformation), new { reservationId = checkIn.ReservationId });
        }

        [HttpGet]
        public async Task<ActionResult> VerifyPaymentInformation(Guid reservationId)
        {
            var roomAllocationResult = await composer.RoomAllocationResult(reservationId);
            if (roomAllocationResult.Result == Result.Failed)
            {
                //if this happens the hotel cannot provide the guest the room type over the time span we promised the guest in the reservation.
                return RedirectToAction(nameof(RoomAllocationFailed));
            }

            //TODO: need to come up with a plan if the room allocation is still in progress. This is b/c of the asynronicity of the AllocateRoom command dispatched earlier in the controller.
            //we could potentiall poll here/use SignalR until we receive the "RoomAllocationResult" and disable the Next button on the UI until we recieve a response?

            var checkIn = (CheckIn)Session[CheckIn];
            checkIn.RoomNumber = roomAllocationResult.RoomNumber;
            Session[CheckIn] = checkIn;

            var model = await composer.ComposePaymentInformation(reservationId);
                        
            return View(model);
        }

        public ActionResult RoomAllocationFailed()
        {
            //if we get here, it means no more physical rooms of the type on the Reservation are available to be allocated
            //the compensating action for the fda would be to create a new Reservation/change their existing reservation 
            //for a different room type and try to find the guest a room, or to call a partnering hotel and have the guest set up there
            return View("RoomAllocationFailed");
        }

        public async Task<ActionResult> DeallocateRoomForNonPayment(Guid reservationId)
        {
            await endpoint.Send(new DeallocateRoomForNonPaymentAtCheckIn { ReservationId = reservationId });
            return RedirectToAction(nameof(HomeController.Index));
        }

        [HttpPost]
        public async Task<ActionResult> VerifyPaymentInformation(PaymentInformation model)
        {
            //if we get here then PlaceHoldOnCreditCardHub sent PlaceHoldOnCreditCardRequest and it prossed correctly. If it didn't, then the user will be stuck on the VerifyPaymentInfo 
            //GET view until a validate credit card is provided
            if (!ModelState.IsValid)
            {
                return View("VerifyPaymentInformation", model);
            }

            var checkIn = (CheckIn)Session[CheckIn];

            await endpoint.Send(new SavePaymentInformation { PaymentInformation = model });
            await endpoint.Send(new Business.RoomInventory.Commands.CheckIn { ReservationId = checkIn.ReservationId });

            return RedirectToAction(nameof(Confirmation), new { roomNumber = checkIn.RoomNumber });
        }

        [HttpGet]
        public ActionResult Confirmation(int roomNumber)
        {
            return View(new Confirmation { RoomNumber = roomNumber });
        }
    }
}

Marriott.Client.Web/Views/CheckIn/Confirmation.cshtml
@using Marriott.Client.Web.Controllers
@model Marriott.Client.Web.Models.CheckIn.Confirmation

@{
    ViewBag.ProgressBar = CheckInController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 4;
}

<div>
    <fieldset>
        <div class="alert alert-success">
            Guest Checked in and assigned Room #@Model.RoomNumber
        </div>
    </fieldset>
</div>

Marriott.Client.Web/Views/CheckIn/Index.cshtml
@using Marriott.Client.Web.Controllers
@model Marriott.Client.Web.Models.CheckIn.Search

@{
    ViewBag.ProgressBar = CheckInController.ProgressBarText;
}

<div>
    <fieldset>
            
        <div class="well">
            Search for a reservation
        </div>

        @using (Html.BeginForm("Index"))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(x => x.Email)
                <p>@Html.TextBoxFor(x => x.Email, new { @class = "form-control" })</p>
            </div>

            <input type="submit" class="btn btn-success" value="Search"/>
        }
    </fieldset>

    <div>&nbsp;</div>

    <fieldset>
        <div>
            @if (Model.SearchExecuted && !Model.Results.Any())
            {
                <div class="alert alert-warning">
                    No results found for the entered criteria. Please try again.
                </div>
            }
            @if (Model.Results.Any())
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>Reservation Id</th>
                            <th>Name</th>
                            <th>Room Type</th>
                            <th>Check In</th>
                            <th>Check Out</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var result in Model.Results)
                        {
                            <tr>
                                <td>@result.ExternalId</td>
                                <td>@result.FullName</td>
                                <td>@result.RoomType</td>
                                <td>@result.CheckIn.ToShortDateString()</td>
                                <td>@result.CheckOut.ToShortDateString()</td>
                                <td>@Html.ActionLink("Begin Check In", nameof(CheckInController.VerifyGuestInformation), new { reservationId = result.ReservationId }, new {  @class = "btn btn-success", role = "button" })</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </fieldset>
</div>

Marriott.Client.Web/Views/CheckIn/RoomAllocationFailed.cshtml
@using Marriott.Client.Web.Controllers

@{
    ViewBag.ProgressBar = CheckInController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 2;
}

<fieldset>
    <div class="alert alert-danger">
        <strong>Room Allocation failed.</strong> 
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        Please <a href="/Reservation/Search" class="alert-link">search for a room</a> with the guest's checkin and checkout date to see if it's still possible to allocate any room to them.
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        If this is not possible, please mark the room allocation as failed and call partnering hotel to find the guest accomodations
    </div>
</fieldset>  

Marriott.Client.Web/Views/CheckIn/VerifyGuestInformation.cshtml
@using Marriott.Client.Web.Controllers

@model Marriott.Client.Web.Models.CheckIn.VerifyGuestInformation

@{
    ViewBag.ProgressBar = CheckInController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 1;
}

<div>
    
    @Html.Action("ReservationInformation", Model.ReservationId)
   
    @using (Html.BeginForm("VerifyGuestInformation", "CheckIn", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.HiddenFor(x => x.ReservationId)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="panel panel-primary">
            <div class="panel-heading">Guest Information</div>
            <div class="panel-body">
                <div class="form-horizontal">
                    @Html.Action("GuestInformation", Model.ReservationId)
                </div>
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    }
</div>

Marriott.Client.Web/Views/CheckIn/VerifyPaymentInformation.cshtml
@using Marriott.Client.Web.Controllers

@model Marriott.Business.Billing.PaymentInformation

@{
    ViewBag.ProgressBar = CheckInController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 2;
}

@section scripts 
{
    <script src="~/Scripts/jquery.signalR-2.2.1.js"></script>
    <script src="~/SignalR/hubs"></script>
    <script src="../../Scripts/CheckIn/placeHoldOnCreditCard.js"></script>
}

<div id="errorMessage" class="alert alert-danger" style="display: none;">
    Hold Failed on credit card. Please try a different credit card.
    <p>&nbsp;</p>
    FDA: if the guest cannot provide a credit card that takes the hold, they cannot check in. In this case, please @(Html.ActionLink("deallocate the room now", "DeallocateRoomForNonPayment", new { Model.ReservationId })).
</div>

<fieldset>
    
    @using (Html.BeginForm("VerifyPaymentInformation", "CheckIn", FormMethod.Post, new { id = "form" }))
    {
        @Html.HiddenFor(x => x.ReservationId)
        <input type="hidden" id="PlaceHoldOnCreditCardFailed" name="PlaceHoldOnCreditCardFailed" value="NotRun"/>

        @Html.Partial("_EditPaymentInformation", Model)

        <div class="form-group">
            <button id="mySubmitButton" type="submit" class="btn btn-success">Continue</button>
            <div id="mySpinner" style="display: none;"><i class="fa fa-spinner fa-spin"></i>
            </div>
        </div>
    }
</fieldset>

Marriott.Client.Web/Views/CheckIn/_ReservationInformation.cshtml
@using Marriott.Client.Web.Extensions

@model Marriott.Client.Web.Models.CheckIn.ReservationInformation

<div class="panel panel-primary">
    <div class="panel-heading">Reservation Id: @Html.DisplayTextFor(x => x.ExternalId)</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-2">@Html.LabelWithColonFor(x => x.CheckIn)</div>
            <div class="col-md-4">@Model.CheckIn.ToShortDateString()</div>
            <div class="col-md-2">@Html.LabelWithColonFor(x => x.TotalNightsOfStay)</div>
            <div class="col-md-4">@Html.DisplayTextFor(x => x.TotalNightsOfStay)</div>
        </div>
        <div class="row">
            <div class="col-md-2">@Html.LabelWithColonFor(x => x.CheckOut)</div>
            <div class="col-md-4">@Model.CheckOut.ToShortDateString()</div>
            <div class="col-md-2">@Html.LabelWithColonFor(x => x.RoomRate)</div>
            <div class="col-md-4">$@Html.DisplayTextFor(x => x.RoomRate)</div>
        </div>
        <div class="row">
            <div class="col-md-2">@Html.LabelWithColonFor(x => x.RoomTypeName)</div>
            <div class="col-md-4">@Html.DisplayTextFor(x => x.RoomTypeName)</div>
            <div class="col-md-2">@Html.LabelWithColonFor(x => x.TotalRoomRate)</div>
            <div class="col-md-4">$@Html.DisplayTextFor(x => x.TotalRoomRate)</div>
        </div>
    </div>
</div>