Marriott.Client.Web/Models/CheckIn/Confirmation.cs
namespace Marriott.Client.Web.Models.CheckIn
{
    public class Confirmation
    {
        public int RoomNumber { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/Search.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class Search
    {
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        public List<SearchResult> Results { get; set; } = new List<SearchResult>();

        public bool SearchExecuted { get; set; }
    }

    public class SearchResult
    {
        public Guid ReservationId { get; set; }
        public int ExternalId { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        public string FullName { get; set; }
        public string RoomType { get; set; }
    }
}

Marriott.Client.Web/Models/CheckOut/Search.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.CheckOut
{
    public class Search
    {
        [Required]
        [DisplayName("Room Number")]
        public int RoomNumber { get; set; }
        public SearchResult Result { get; set; }
        public bool SearchExecuted { get; set; }
    }

    public class SearchResult
    {
        public Guid ReservationId { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        [DisplayName("Guest Name")]
        public string GuestFullName { get; set; }
    }
}

Marriott.Client.Web/Models/Reservation/Reservation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using Marriott.Business.Billing;
using Marriott.Business.Guest;

namespace Marriott.Client.Web.Models.Reservation
{
    public class Reservation
    {
        public Guid ReservationId { get; set; }

        [DisplayName("Check In")]
        public DateTime CheckIn { get; set; }

        [DisplayName("Check Out")]
        public DateTime CheckOut { get; set; }

        public int RoomTypeId { get; set; }

        public RoomInformation RoomInformation { get; set; }

        public GuestInformation GuestInformation { get; set; }

        public PaymentInformation PaymentInformation { get; set; }

        public List<RoomTypeIdRoomTotalAndTotalRoomRate> RoomTypeIdRoomTotalAndTotalRoomRates { get; set; } = new List<RoomTypeIdRoomTotalAndTotalRoomRate>();

        public int TimeLeftOnPendingReservation { get; set; }
    }

    public class RoomTypeIdRoomTotalAndTotalRoomRate
    {
        public int RoomTypeId { get; set; }
        public double RoomRate { get; set; }
        public double TotalRoomRate { get; set; }
    }
}

Marriott.Client.Web/Models/Reservation/RoomInformation.cs
using System.ComponentModel;

namespace Marriott.Client.Web.Models.Reservation
{
    public class RoomInformation
    {
        [DisplayName("Room Type")]
        public string RoomTypeName { get; set; }
        
        [DisplayName("Room Rate")]
        public double RoomRate { get; set; }

        [DisplayName("Total Room Rate")]
        public double TotalRoomRate { get; set; }
    }
}

Marriott.Client.Web/Models/Reservation/Search.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.Reservation
{
    public class Search
    {
        [Required]
        [DisplayName("Check In")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime CheckIn { get; set; } = DateTime.Now.Date;

        [Required]
        [DisplayName("Check Out")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime CheckOut { get; set; } = DateTime.Now.AddDays(5).Date;

        public List<SearchResult> Results { get; set; } = new List<SearchResult>();

        public bool SearchExecuted { get; set; }
        public bool CheckOutDateIsTheSameDayAsOrBeforeCheckInDate { get; set; }
    }

    public class SearchResult
    {
        [DisplayName("Room Type")]
        public int RoomTypeId { get; set; }

        [DisplayName("Room Type")]
        public string RoomTypeName { get; set; }

        public string ImageUrl { get; set; }

        [DisplayName("Description")]
        public string RoomDescription { get; set; }

        [DisplayName("Rate")]
        public double RoomRate { get; set; }

        public double TotalRoomRate { get; set; }
    }
}

Marriott.Client.Web/Controllers/ReservationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Marriott.Business.Billing;
using Marriott.Business.Billing.Commands;
using Marriott.Business.Guest;
using Marriott.Business.Guest.Commands;
using Marriott.Business.Pricing;
using Marriott.Business.Pricing.Commands;
using Marriott.Business.Reservation.Commands;
using Marriott.Client.Web.Composers.Reservation;
using Marriott.Client.Web.Extensions;
using Marriott.Client.Web.Models.Reservation;
using Marriott.ITOps.PaymentGateway;
using NServiceBus;
using Reservation = Marriott.Client.Web.Models.Reservation.Reservation;

namespace Marriott.Client.Web.Controllers
{
    public class ReservationController : Controller
    {
        private const string Reservation = "reservation";
        private const string TimeLeftOnPendingReservation = "TimeLeftOnPendingReservation";
        public static readonly string ProgressBarText = "Search, Guest Information, Payment Information, Review, Confirmation";

        private readonly IEndpointInstance endpoint;
        private readonly ReservationComposer composer;
        public Func<Guid> CreateReservationId = () => Guid.NewGuid();

        public ReservationController(IEndpointInstance endpoint, ICreditCardService creditCardService, ReservationComposer composer)
        {
            this.endpoint = endpoint;
            this.composer = composer;
            ViewBag.ActiveNavBarItem = NavigationBarItem.Reservations;
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View(new Search());
        }

        [HttpPost]
        public async Task<ActionResult> Search(Search model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.CheckOut.Date <= model.CheckIn.Date)
            {
                model.CheckOutDateIsTheSameDayAsOrBeforeCheckInDate = true;
                return View(model);
            }

            model = await composer.ComposeSearch(model);
            model.SearchExecuted = true;

            //Why am I doing this?
            //I'm showing the user room rates based on their search results. When the user picks a room and the page posts back, if I were to re-compose room rate information and it's 
            //different than what the user was shown on the search resuls, that's bad. By committing all possible room rate information to session for each search result returned, I can 
            //guarantee that price to the user even if rates were to change between the point they viewed the search results, picked a room and confirmed their reservation
            var reservation = new Reservation { CheckIn = model.CheckIn, CheckOut = model.CheckOut };
            foreach (var result in model.Results)
            {
                reservation.RoomTypeIdRoomTotalAndTotalRoomRates.Add(new RoomTypeIdRoomTotalAndTotalRoomRate { RoomTypeId = result.RoomTypeId, RoomRate = result.RoomRate, TotalRoomRate = result.TotalRoomRate });
            }
            Session[Reservation] = reservation;

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> SelectRoom(int roomTypeId)
        {
            var reservationId = CreateReservationId();

            var reservation = (Reservation)Session[Reservation];

            var selectedRoomRateAndTotalRoomRate = reservation.RoomTypeIdRoomTotalAndTotalRoomRates.Single(x => x.RoomTypeId == roomTypeId);

            reservation.ReservationId = reservationId;
            reservation.RoomTypeId = roomTypeId;
            reservation.RoomInformation = await composer.ComposeRoomInformationFor(roomTypeId, selectedRoomRateAndTotalRoomRate.RoomRate, selectedRoomRateAndTotalRoomRate.TotalRoomRate);
            Session[Reservation] = reservation;

            //Reservation Pattern (http://arnon.me/soa-patterns/reservation/)
            await endpoint.Send(new CreatePendingReservation { ReservationId = reservationId, RoomTypeId = roomTypeId, CheckIn = reservation.CheckIn, CheckOut = reservation.CheckOut });
            await endpoint.Send(new SaveReservationRoomRate { ReservationRoomRate = new ReservationRoomRate
            {
                ReservationId = reservationId,
                RoomRate = selectedRoomRateAndTotalRoomRate.RoomRate,
                TotalRoomRate = selectedRoomRateAndTotalRoomRate.TotalRoomRate
            }});

            return RedirectToAction(nameof(GuestInformation), new { roomTypeId });
        }

        [HttpGet]
        public ActionResult GuestInformation(int roomTypeId)
        {
            var reservation = (Reservation)Session[Reservation];
            reservation.TimeLeftOnPendingReservation = 900;
            Session[Reservation] = reservation;

            ViewBag.TimeLeftOnPendingReservation = reservation.TimeLeftOnPendingReservation;
            return View(new GuestInformation());
        }

        [HttpPost]
        public async Task<ActionResult> GuestInformation(GuestInformation model)
        {
            UpdateTimeLeftOnPendingReservationFromRequestFormToToSession();

            if (!ModelState.IsValid)
            {
                AssignTimeLeftOnPendingReservationFromRequestFormToViewBag();
                return View(model);
            }

            var reservation = (Reservation)Session[Reservation];
            model.ReservationId = reservation.ReservationId;
            reservation.GuestInformation = model;
            Session[Reservation] = reservation;

            await endpoint.Send(new SaveGuestInformation { GuestInformation = model });

            return RedirectToAction(nameof(Payment));
        }

        //http://www.marriott.com/help/reserve-faqs.mi
        //Why do I need a credit card number to reserve a room?
        //Marriott.com requires all room reservations to be guaranteed by a valid credit card. Your credit card is not charged at the time of reservation, and is used as a guarantee 
        //that a room will be held in advance of your arrival. Your credit card will be charged only if pre-payment is required for a specific rate, or in the event that you do not 
        //cancel your reservation within the stated cancellation time period and do not check in.
        [HttpGet]
        public ActionResult Payment()
        {
            AssignTimeLeftOnPendingReservationFromSessionToViewBag();
            return View(new PaymentInformation());
        }

        [HttpPost]
        public async Task<ActionResult> Payment(PaymentInformation model)
        {
            UpdateTimeLeftOnPendingReservationFromRequestFormToToSession();

            if (!ModelState.IsValid)
            {
                AssignTimeLeftOnPendingReservationFromRequestFormToViewBag();
                return View(model);
            }

            var reservation = (Reservation)Session[Reservation];

            model.ReservationId = reservation.ReservationId;
            await endpoint.Send(new SavePaymentInformation { PaymentInformation = model });

            reservation.PaymentInformation = model;
            Session[Reservation] = reservation;

            return RedirectToAction(nameof(Review));
        }

        [HttpGet]
        public ActionResult Review()
        {
            AssignTimeLeftOnPendingReservationFromSessionToViewBag();
            return View((Reservation) Session[Reservation]);
        }

        [HttpPost]
        public async Task<ActionResult> Reserve(Reservation model)
        {
            var reservation = (Reservation)Session[Reservation];

            //I don't need to make this check anymore, b/c PendingReservation offers a limited, time-based lock on the "resource", which here, is a room type over a given timespan
            //if (!await composer.IsRoomStillAvailableFor(reservation.CheckIn, reservation.CheckOut, reservation.RoomTypeId))
            //{
            //    return View("RoomNoLongerAvailable", (Reservation) Session[Reservation]);
            //}

            await endpoint.Send(new ConfirmPendingReservation { ReservationId = reservation.ReservationId });

            //clean up session
            Session.Remove(Reservation);

            TempData[Reservation] = reservation;
            return RedirectToAction(nameof(Confirmation));
        }

        [HttpGet]
        public ActionResult Confirmation()
        {
            return View((Reservation)TempData[Reservation]);
        }

        [HttpGet]
        public async Task<ActionResult>PendingReservationTimeOut()
        {
            var reservation = (Reservation)Session[Reservation];
            await endpoint.Send(new CancelPendingReservation { ReservationId = reservation.ReservationId });
            Session.Remove(Reservation);

            return RedirectToAction("Search");
        }

        private void UpdateTimeLeftOnPendingReservationFromRequestFormToToSession()
        {
            var reservation = (Reservation)Session[Reservation];
            reservation.TimeLeftOnPendingReservation = Convert.ToInt32(Request.Form[TimeLeftOnPendingReservation]);
            Session[Reservation] = reservation;
        }

        private void AssignTimeLeftOnPendingReservationFromSessionToViewBag()
        {
            var reservation = (Reservation)Session [Reservation];
            ViewBag.TimeLeftOnPendingReservation = reservation.TimeLeftOnPendingReservation;
        }

        private void AssignTimeLeftOnPendingReservationFromRequestFormToViewBag()
        {
            ViewBag.TimeLeftOnPendingReservation = Convert.ToInt32(Request.Form[TimeLeftOnPendingReservation]);
        }
    }
}

Marriott.Client.Web/Views/Reservation/Confirmation.cshtml
@using Marriott.Client.Web.Controllers
@model Marriott.Client.Web.Models.Reservation.Reservation

@{
    ViewBag.ProgressBar = ReservationController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 4;
}

<div>
    <div class="alert alert-success">
        Thank you for booking with us! You will recive an email shortly where you can access your reservation details, change your reservation or cancel your reservation
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">Reservation Details</div>
        <div class="panel-body">

            <div class="row">
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading"><strong>Room Details</strong></div>
                        <div class="panel-body" style="min-height: 250px;">
                            @Html.LabelFor(x => x.RoomInformation.RoomTypeName): @Model.RoomInformation.RoomTypeName<br />
                            @Html.LabelFor(x => x.CheckIn): @Model.CheckIn.ToShortDateString()<br />
                            @Html.LabelFor(x => x.CheckOut): @Model.CheckOut.ToShortDateString()<br />
                            @Html.LabelFor(x => x.RoomInformation.RoomRate): $@Model.RoomInformation.RoomRate.ToString()
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading"><strong>Guest Information</strong></div>
                        <div class="panel-body" style="min-height: 250px;">
                            @Html.LabelFor(x => x.GuestInformation.Email): @Model.GuestInformation.Email<br />
                            @Html.LabelFor(x => x.GuestInformation.FirstName): @Model.GuestInformation.FirstName<br />
                            @Html.LabelFor(x => x.GuestInformation.LastName): @Model.GuestInformation.LastName<br />
                            @Html.LabelFor(x => x.GuestInformation.Address1): @Model.GuestInformation.Address1<br />
                            @Html.LabelFor(x => x.GuestInformation.Address2): @Model.GuestInformation.Address2<br />
                            @Html.LabelFor(x => x.GuestInformation.City): @Model.GuestInformation.City<br />
                            @Html.LabelFor(x => x.GuestInformation.State): @Model.GuestInformation.State<br />
                            @Html.LabelFor(x => x.GuestInformation.PostalCode): @Model.GuestInformation.PostalCode
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading"><strong>Payment Information</strong></div>
                        <div class="panel-body" style="min-height: 250px;">
                            @Html.LabelFor(x => x.PaymentInformation.CreditCardNumber): @Model.PaymentInformation.CreditCardNumber<br />
                            @Html.LabelFor(x => x.PaymentInformation.CreditCardExpiry): @Model.PaymentInformation.CreditCardExpiry<br />
                            @Html.LabelFor(x => x.PaymentInformation.CreditCardCcv): @Model.PaymentInformation.CreditCardCcv<br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Marriott.Client.Web/Views/Reservation/GuestInformation.cshtml
@using Marriott.Client.Web.Controllers

@model  Marriott.Business.Guest.GuestInformation 

@{
    ViewBag.ProgressBar = ReservationController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 1;
}

@section scripts
{
    <script src="~/Scripts/Reservation/timeLeftOnPendingReservation.js"></script>
    <script>
        CountDownTimer(@ViewBag.TimeLeftOnPendingReservation);

        ////this only handles F5 and ctrl + R. I need a way to handle the browser's refresh button
        ////http://stackoverflow.com/questions/2482059/disable-f5-and-browser-refresh-using-javascript
        //function refresh(e)
        //{
        //    if (((e.which || e.keyCode) == 116) || (e.keyCode == 82 && e.ctrlKey))
        //    {
        //        alert('page reloading is disabled');
        //        e.preventDefault();
        //    }
        //};
        //$(document).bind("keydown", refresh);

        //2
        //window.onbeforeunload = function () {
        //    return "Are you sure you want to leave our website?";
        //}

        //$(function () {
        //    $('a, input, button').click(function () {
        //        window.onbeforeunload = null;
        //    });
        //});

        //1
        //$(window).bind('beforeunload', function () {
        //    //save info somewhere
        //    var timeLeftOnPendingReservation = $('#TimeLeftOnPendingReservation').val();
        //    return 'are you sure you want to leave?';
        //});

    </script>
}

<div>
    <fieldset>
        
        <div class="well">
            <div class="row">
                <div class="col-md-2">Enter your information</div>
                <div class="col-md-8">&nbsp;</div>
                <div class="col-md-2"><div id="Counter" name="Counter"></div></div>
            </div>
        </div>

        @using (Html.BeginForm("GuestInformation", "Reservation", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <input type="hidden" id="TimeLeftOnPendingReservation" name="TimeLeftOnPendingReservation" value="@ViewBag.TimeLeftOnPendingReservation">

            @Html.Partial("_EditGuestInformation", Model)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success">Next</button>
                </div>
            </div>
        }
    </fieldset>
</div>

Marriott.Client.Web/Views/Reservation/Payment.cshtml
@using Marriott.Business.Billing
@using Marriott.Client.Web.Controllers

@model PaymentInformation

@{
    ViewBag.ProgressBar = ReservationController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 2;
}

@section scripts 
{
    <script src="~/Scripts/jquery.signalR-2.2.1.js"></script>
    <script src="~/SignalR/hubs"></script>
    <script src="~/Scripts/Reservation/validateCreditCard.js"></script>
    <script src="~/Scripts/Reservation/timeLeftOnPendingReservation.js"></script>
    <script>
        CountDownTimer(@ViewBag.TimeLeftOnPendingReservation);
    </script>    
}

<fieldset>
    
    <div id="errorMessage" class="alert alert-danger" style="display: none;">
        Credit Card Validation Failed
    </div>
    
    <div class="well">
        <div class="row">
            <div class="col-md-3">Enter your payment information</div>
            <div class="col-md-7">&nbsp;</div>
            <div class="col-md-2"><div id="Counter" name="Counter"></div></div>
        </div>
    </div>

    @using (Html.BeginForm("Payment", "Reservation", FormMethod.Post, new { id = "form" }))
    {
        <input type="hidden" id="TimeLeftOnPendingReservation" name="TimeLeftOnPendingReservation" value="@ViewBag.TimeLeftOnPendingReservation">
        <input type="hidden" id="CreditCardCheckFailed" name="CreditCardCheckFailed" value="NotRun"/>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_EditPaymentInformation", Model)

        <div class="form-group">
            <button id="mySubmitButton" type="submit" class="btn btn-success">Next</button>
            <div id="mySpinner" style="display: none;"><i class="fa fa-spinner fa-spin"></i></div>
        </div>
    }

</fieldset>

Marriott.Client.Web/Views/Reservation/Review.cshtml
@using Marriott.Client.Web.Controllers
@model Marriott.Client.Web.Models.Reservation.Reservation

@{
    ViewBag.ProgressBar = ReservationController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 3;
}

@section scripts
{
    <script src="~/Scripts/Reservation/timeLeftOnPendingReservation.js"></script>
    <script>
        CountDownTimer(@ViewBag.TimeLeftOnPendingReservation);
    </script>
}

<div>
    <fieldset>
               
        <div class="well">
            <div class="row">
                <div class="col-md-3">Please review all your information</div>
                <div class="col-md-7">&nbsp;</div>
                <div class="col-md-2"><div id="Counter" name="Counter"></div></div>
            </div>
        </div>

        @using (Html.BeginForm("Reserve", "Reservation"))
        {
            <input type="hidden" id="TimeLeftOnPendingReservation" name="TimeLeftOnPendingReservation" value="@ViewBag.TimeLeftOnPendingReservation">

            <div class="row">
                <div class="col-md-4">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Room Details</div>
                        <div class="panel-body" style="min-height: 250px;">
                            <div class="field inline">
                                @Html.LabelFor(x => x.CheckIn): @Model.CheckIn.ToShortDateString()
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.CheckOut): @Model.CheckOut.ToShortDateString()
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.RoomInformation.RoomTypeName): @Html.DisplayTextFor(x => x.RoomInformation.RoomTypeName)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.RoomInformation.RoomRate): $@Html.DisplayTextFor(x => x.RoomInformation.RoomRate)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.RoomInformation.TotalRoomRate): $@Html.DisplayTextFor(x => x.RoomInformation.TotalRoomRate)
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-md-4">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Guest Information</div>
                        <div class="panel-body" style="min-height: 250px;">
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.Email): @Html.DisplayTextFor(x => x.GuestInformation.Email)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.FirstName): @Html.DisplayTextFor(x => x.GuestInformation.FirstName)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.LastName): @Html.DisplayTextFor(x => x.GuestInformation.LastName)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.Address1): @Html.DisplayTextFor(x => x.GuestInformation.Address1)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.Address2): @Html.DisplayTextFor(x => x.GuestInformation.Address2)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.City): @Html.DisplayTextFor(x => x.GuestInformation.City)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.State): @Html.DisplayTextFor(x => x.GuestInformation.State)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.GuestInformation.PostalCode): @Html.DisplayTextFor(x => x.GuestInformation.PostalCode)
                            </div>
                        </div>
                    </div>

                </div>
                
                <div class="col-md-4">
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">Payment Information</div>
                        <div class="panel-body" style="min-height: 250px;">
                            <div class="field inline">
                                @Html.LabelFor(x => x.PaymentInformation.CreditCardNumber): @Html.DisplayTextFor(x => x.PaymentInformation.CreditCardNumber)
                            </div>
                            <div class="field inline">
                                @Html.Label("Credit Card Expiration"): @Html.DisplayTextFor(x => x.PaymentInformation.CreditCardExpiryMonth)/@Html.DisplayTextFor(x => x.PaymentInformation.CreditCardExpiryYear)
                            </div>
                            <div class="field inline">
                                @Html.LabelFor(x => x.PaymentInformation.CreditCardCcv): @Html.DisplayTextFor(x => x.PaymentInformation.CreditCardCcv)
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            
            <div class="form-group">
                <input type="submit" class="btn btn-success" value="Book Now" />
            </div>
        }
    </fieldset>
</div>

Marriott.Client.Web/Views/Reservation/Search.cshtml
@using Marriott.Client.Web.Controllers
@model Marriott.Client.Web.Models.Reservation.Search

@{
    ViewBag.ProgressBar = ReservationController.ProgressBarText;
}

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script>
    $( function() {
        $("#checkInDatePicker").datepicker({ minDate: 0 });
        $("#checkOutDatePicker").datepicker({ minDate: "+1d" });
    });
</script>

<div>
    <fieldset>
        
        @if (Model.CheckOutDateIsTheSameDayAsOrBeforeCheckInDate)
        {
            <div class="alert alert-danger">
                Check Out date can not be the same day or before Check In date
            </div>
        }

        <div class="panel panel-default">
            <div class="panel-heading">Seach for a Room</div>
            <div class="panel-body">
                @using (Html.BeginForm("Search"))
                {
                    <div class="form-group">
                        @Html.LabelFor(x => x.CheckIn)
                        <p>@Html.EditorFor(x => x.CheckIn, new { htmlAttributes = new { @class = "form-control", id = "checkInDatePicker" } })</p>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.CheckOut)
                        <p>@Html.EditorFor(x => x.CheckOut, new { htmlAttributes = new { @class = "form-control", id = "checkOutDatePicker" }})</p>
                    </div>

                    <input type="submit" class="btn btn-success" value="Search" />
                }
            </div>
        </div>

    </fieldset>
    
    <div>&nbsp;</div>
    
    <fieldset>
        <div>
            @if (Model.SearchExecuted && !Model.Results.Any())
            {
                <div class="alert alert-warning">
                    No results found for those dates. Please try again.
                </div>
            }
            @if (Model.Results.Any())
            {
                <div class="panel panel-default">
                    <div class="panel-heading">Results</div>
                    <div class="panel-body">
                        <table class="table">
                            <tbody>
                                @foreach (var result in Model.Results)
                                {
                                    using (Html.BeginForm(nameof(ReservationController.SelectRoom), "Reservation", FormMethod.Post))
                                    {
                                        @Html.Hidden("roomTypeId", result.RoomTypeId)
                                        <tr>
                                            <td>
                                                Room Description: @Html.Label(result.RoomDescription)<br />
                                                Room Rate: @Html.Label(result.RoomRate.ToString()) USD/night (<b>@result.TotalRoomRate</b> total)<br />
                                                <input type="submit" class="btn btn-success" value="Select Room">
                                            </td>
                                            <td>
                                                <img src="@result.ImageUrl"/>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            }
        </div>
    </fieldset>

</div>