Marriott.Client.Web/Models/Housekeeping/Index.cs
using System;
using System.Collections.Generic;

namespace Marriott.Client.Web.Models.Housekeeping
{
    public class Index
    {
        public List<Room> Rooms { get; set; } = new List<Room>();
    }

    public class Room
    {
        public int RoomNumber { get; set; }
        public bool Clean { get; set; }
        public DateTime DateTimeCheckedOut { get; set; }
    }
}

Marriott.Client.Web/Controllers/HousekeepingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Marriott.Client.Web.Composers.Housekeeping;
using Marriott.Client.Web.Models.Housekeeping;
using NServiceBus;
using System.Threading.Tasks;
using Marriott.Business.Housekeeping;
using Marriott.Business.Housekeeping.Commands;
using Marriott.Client.Web.Extensions;

namespace Marriott.Client.Web.Controllers
{
    public class HousekeepingController : Controller
    {
        private readonly IEndpointInstance endpoint;
        private readonly HousekeepingComposer composer;

        public HousekeepingController(IEndpointInstance endpoint, HousekeepingComposer composer)
        {
            this.endpoint = endpoint;
            this.composer = composer;
            ViewBag.ActiveNavBarItem = NavigationBarItem.Housekeeping;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var model = await composer.ComposeRoomsThatNeedToBeCleanedToday();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(Index model)
        {
            var todaysCleanRooms = model.Rooms.Where(x => x.Clean).Select(x => new TodaysCleanRooms
            {
                RoomNumber = x.RoomNumber,
                DayCleaned = DateTime.Now.Date
            }).ToList();

            await endpoint.Send(new UpdateTodaysCleanRooms { TodaysCleanRooms = todaysCleanRooms });

            return View("Index", model);
        }
    }
}

Marriott.Client.Web/Views/Housekeeping/Index.cshtml
@using System.Web.Mvc.Html
@using Marriott.Client.Web.Extensions
@model Marriott.Client.Web.Models.Housekeeping.Index

<div>
    
    <div class="well">
        Rooms and their clean status as of <strong>@DateTime.Now.Date.ToShortDateString()</strong>
    </div>

    @using (Html.BeginForm("Index", "Housekeeping"))
    {
        <table>
            @for (var i = 0; i < Model.Rooms.Count; i++)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(m => m.Rooms[i].RoomNumber)
                        @Html.CheckBoxFor(m => m.Rooms[i].Clean, $"Room {Model.Rooms[i].RoomNumber}", new {}, false)        
                    </td>
                </tr>
            }
        </table>

        <p></p>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    }
</div>