Marriott.Client.Web/Models/CheckIn/Confirmation.cs
namespace Marriott.Client.Web.Models.CheckIn
{
    public class Confirmation
    {
        public int RoomNumber { get; set; }
    }
}

Marriott.Client.Web/Models/CheckIn/Search.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.CheckIn
{
    public class Search
    {
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        public List<SearchResult> Results { get; set; } = new List<SearchResult>();

        public bool SearchExecuted { get; set; }
    }

    public class SearchResult
    {
        public Guid ReservationId { get; set; }
        public int ExternalId { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        public string FullName { get; set; }
        public string RoomType { get; set; }
    }
}

Marriott.Client.Web/Models/CheckOut/Search.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.CheckOut
{
    public class Search
    {
        [Required]
        [DisplayName("Room Number")]
        public int RoomNumber { get; set; }
        public SearchResult Result { get; set; }
        public bool SearchExecuted { get; set; }
    }

    public class SearchResult
    {
        public Guid ReservationId { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        [DisplayName("Guest Name")]
        public string GuestFullName { get; set; }
    }
}

Marriott.Client.Web/Models/CheckOut/VerifyInvoice.cs
using System;
using System.ComponentModel;
using Marriott.Business.Billing;
using Marriott.Business.Guest;

namespace Marriott.Client.Web.Models.CheckOut
{
    //http://l.yimg.com/a/p/sp/tools/med/2010/09/ipt/1285725603.jpg
    public class VerifyInvoice
    {
        public const double RoomTaxRate = .08;

        public Guid ReservationId { get; set; }

        [DisplayName("Room #")]
        public int RoomNumber { get; set; }

        public GuestInformation GuestInformation { get; set; }

        public PaymentInformation PaymentInformation { get; set; }

        [DisplayName("Room Type")]
        public string RoomType { get; set; }

        [DisplayName("Check In")]
        public DateTime CheckIn { get; set; }

        [DisplayName("Check Out")]
        public DateTime CheckOut { get; set; }

        [DisplayName("Rate")]
        public double RoomRate { get; set; }

        [DisplayName("Room Total")]
        public double TotalRoomRate { get; set; }

        public double Tax { get; set; }

        public double Total { get; set; }

        //public double Tax => TotalRoomRate * RoomTaxRate;
        //public double Total => TotalRoomRate + Tax;
    }
}

Marriott.Client.Web/Models/Reservation/Search.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Marriott.Client.Web.Models.Reservation
{
    public class Search
    {
        [Required]
        [DisplayName("Check In")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime CheckIn { get; set; } = DateTime.Now.Date;

        [Required]
        [DisplayName("Check Out")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime CheckOut { get; set; } = DateTime.Now.AddDays(5).Date;

        public List<SearchResult> Results { get; set; } = new List<SearchResult>();

        public bool SearchExecuted { get; set; }
        public bool CheckOutDateIsTheSameDayAsOrBeforeCheckInDate { get; set; }
    }

    public class SearchResult
    {
        [DisplayName("Room Type")]
        public int RoomTypeId { get; set; }

        [DisplayName("Room Type")]
        public string RoomTypeName { get; set; }

        public string ImageUrl { get; set; }

        [DisplayName("Description")]
        public string RoomDescription { get; set; }

        [DisplayName("Rate")]
        public double RoomRate { get; set; }

        public double TotalRoomRate { get; set; }
    }
}

Marriott.Client.Web/Controllers/CheckOutController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Marriott.Business.RoomInventory.Commands;
using Marriott.Client.Web.Composers.CheckOut;
using Marriott.Client.Web.Extensions;
using Marriott.Client.Web.Models.CheckOut;
using NServiceBus;

namespace Marriott.Client.Web.Controllers
{
    public class CheckOutController : Controller
    {
        public static readonly string ProgressBarText = "Search, Verify Invoice and Payment Method, Confirmation";

        private readonly IEndpointInstance endpoint;
        private readonly CheckOutComposer composer;

        public CheckOutController(IEndpointInstance endpoint, CheckOutComposer composer)
        {
            this.endpoint = endpoint;
            this.composer = composer;
            ViewBag.ActiveNavBarItem = NavigationBarItem.FrontDesk;
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View(new Search());
        }

        [HttpPost]
        public async Task<ActionResult> Search(Search model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model = await composer.ComposeSearchResults(model);
            model.SearchExecuted = true;

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> VerifyInvoice(Guid reservationId)
        {
            var model = await composer.ComposeVerifyInvoice(reservationId);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> VerifyInvoice(VerifyInvoice model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await endpoint.Send(new CheckOut { ReservationId = model.ReservationId, CheckOutDate = DateTime.Now });

            return RedirectToAction(nameof(Confirmation));
        }

        [HttpGet]
        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

Marriott.Client.Web/Views/CheckOut/Confirmation.cshtml
@using Marriott.Client.Web.Controllers

@{
    ViewBag.ProgressBar = CheckOutController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 2;
}

<div class="container">
    <div class="panel-group">
        <div class="panel panel-success">
            <div class="panel-heading">Payment Processed and Checked Out</div>
            <div class="panel-body">Thanks for staying with us!</div>
        </div>
    </div>
</div>

Marriott.Client.Web/Views/CheckOut/Search.cshtml
@using Marriott.Client.Web.Controllers
@using Marriott.Client.Web.Extensions
@using Marriott.Client.Web.Models.CheckOut
@model Search

@{
    ViewBag.ProgressBar = CheckOutController.ProgressBarText;
}

    <fieldset>

        <div class="well">
            Search by Room Number
        </div>

        @using (Html.BeginForm("Search", "CheckOut"))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(x => x.RoomNumber)
                @Html.TextBoxWithBlankDefaultIntegerValue(nameof(Search.RoomNumber), Model.RoomNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.RoomNumber, "", new { @class = "text-danger" })
            </div>

            <input type="submit" class="btn btn-success" value="Search" />
        }

    </fieldset>
    
    <div>&nbsp;</div>
    
    <fieldset>
        <div>
            @if (Model.SearchExecuted && Model.Result == null)
            {
                <div class="alert alert-warning">
                    No results found for the entered Room Number. Please try again.
                </div>
            }

            @if (Model.Result != null)
            {
                <div class="panel panel-primary">
                    <div class="panel-heading">Guest Information</div>

                    <div class="panel-body">
                        <div class="field inline">
                            @Html.LabelFor(x => x.RoomNumber): @Html.DisplayTextFor(x => x.RoomNumber)
                        </div>
                        <div class="field inline">
                            @Html.LabelFor(x => x.Result.GuestFullName): @Html.DisplayTextFor(x => x.Result.GuestFullName)
                        </div>
                        <div class="field inline">
                            @Html.LabelFor(x => x.Result.CheckIn): @Model.Result.CheckIn.ToShortDateString()
                        </div>
                        <div class="field inline">
                            @Html.LabelFor(x => x.Result.CheckOut): @Model.Result.CheckOut.ToShortDateString()
                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success" onclick="location.href='@Url.Action("VerifyInvoice", "CheckOut", new { reservationId = Model.Result.ReservationId })'">Continue</button>
                </div>
            }
        </div>
    </fieldset>

Marriott.Client.Web/Views/CheckOut/VerifyInvoice.cshtml
@using Marriott.Client.Web.Controllers
@using Marriott.Client.Web.Extensions
@model Marriott.Client.Web.Models.CheckOut.VerifyInvoice

@{
    ViewBag.ProgressBar = CheckOutController.ProgressBarText;
    ViewBag.ProgressBarActiveNode = 1;
}

<div>
    <fieldset>
        
        <div class="panel panel-primary">
            <div class="panel-heading"><strong>INVOICE</strong>
            </div>
            <div class="panel-body">
                <div class="row">

                    <!-- Guest Information -->
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">Guest Information</div>
                            <div class="panel-body" style="min-height: 110px;">
                                @Model.GuestInformation.FullName<br/>
                                @Model.GuestInformation.Address1<br/>
                                @Model.GuestInformation.Address2<br/>
                                @Model.GuestInformation.City @Model.GuestInformation.State @Model.GuestInformation.PostalCode
                            </div>
                        </div>
                    </div>

                    <!-- Payment Information -->
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">Payment Information</div>
                            <div class="panel-body" style="min-height: 110px;">
                                @Html.LabelWithColonFor(x => x.PaymentInformation.CreditCardNumber) @Html.DisplayTextFor(x => x.PaymentInformation.CreditCardNumber)<br/>
                                @Html.LabelWithColonFor(x => x.PaymentInformation.CreditCardExpiry) @Html.DisplayTextFor(x => x.PaymentInformation.CreditCardExpiry)
                            </div>
                        </div>
                    </div>

                    <!-- Room Information -->
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">Room Information</div>
                            <div class="panel-body" style="min-height: 110px;">
                                @Html.LabelWithColonFor(x => x.RoomNumber) @Model.RoomNumber<br/>
                                @Html.LabelWithColonFor(x => x.RoomType) @Model.RoomType<br/>
                                @Html.LabelWithColonFor(x => x.RoomRate) $@Model.RoomRate
                            </div>
                        </div>
                    </div>

                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Your Stay</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3">@Html.LabelWithColonFor(x => x.CheckIn) @Model.CheckIn.ToShortDateString()</div>
                            <div class="col-md-3">Time: TIME</div>
                            <div class="col-md-3">@Html.LabelWithColonFor(x => x.CheckOut) @Model.CheckOut.ToShortDateString()</div>
                            <div class="col-md-3">Time: TIME</div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Charges</div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Description</th>
                                <th>&nbsp;</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>@DateTime.Now.AddDays(-2).Date.ToShortDateString()</td>
                                <td>Room Charge</td>
                                <td>&nbsp;</td>
                                <td>$120.00</td>
                            </tr>
                            <tr>
                                <td>@DateTime.Now.AddDays(-2).Date.ToShortDateString()</td>
                                <td>State Occupancy Tax</td>
                                <td>&nbsp;</td>
                                <td>$17.90</td>
                            </tr>
                            <tr>
                                <td>@DateTime.Now.AddDays(-2).Date.ToShortDateString()</td>
                                <td>Movie</td>
                                <td>&nbsp;</td>
                                <td>$14.99</td>
                            </tr>
                            <tr>
                                <td>@DateTime.Now.AddDays(-1).Date.ToShortDateString()</td>
                                <td>Room Charge</td>
                                <td>&nbsp;</td>
                                <td>$120.00</td>
                            </tr>
                            <tr>
                                <td>@DateTime.Now.AddDays(-1).Date.ToShortDateString()</td>
                                <td>State Occupancy Tax</td>
                                <td>&nbsp;</td>
                                <td>$17.90</td>
                            </tr>
                            <tr>
                                <td>@DateTime.Now.AddDays(-1).Date.ToShortDateString()</td>
                                <td>Movie</td>
                                <td>&nbsp;</td>
                                <td>$14.99</td>
                            </tr>
                            <!--sub total and totals-->
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td><strong>Subtotal</strong></td>
                                <td>0.00</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td><strong>Tax</strong></td>
                                <td>0.00</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td><strong>Total Due</strong></td>
                                <td>0.00</td>
                            </tr>
                            <!--sub total and totals-->
                            </tbody>
                        </table>
                    </div>
                </div>

                <div>
                    @using (Html.BeginForm("VerifyInvoice"))
                    {
                        @Html.HiddenFor(x => x.ReservationId)
                        @Html.HiddenFor(x => x.RoomNumber)
                        @Html.HiddenFor(x => x.Total)

                        <div class="form-group">
                            <input type="submit" class="btn btn-success" value="Confirm Invoice and Check Out"/>
                        </div>
                    }
                </div>

            </div>
        </div>

    </fieldset>
</div>